[project]
name = 'Decentralized-Regulatory-Change-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attestation]
path = 'contracts/attestation.clar'
clarity_version = 2
epoch = 2.5

[contracts.impact-assessment]
path = 'contracts/impact-assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.implementation-tracking]
path = 'contracts/implementation-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.regulatory-source-verification]
path = 'contracts/regulatory-source-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.requirement-tracking]
path = 'contracts/requirement-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
